# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clexicon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='clexicon.proto',
  package='clexicon',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63lexicon.proto\x12\x08\x63lexicon\"G\n\nMorphology\x12\x16\n\x0emorph_features\x18\x01 \x03(\t\x12!\n\x07\x63litics\x18\x02 \x03(\x0b\x32\x10.clexicon.Clitic\"0\n\x06\x43litic\x12\x0e\n\x06\x63litic\x18\x01 \x01(\t\x12\x16\n\x0emorph_features\x18\x02 \x03(\t\"A\n\rPronunciation\x12\r\n\x05phone\x18\x01 \x03(\t\x12\x0f\n\x07segment\x18\x02 \x03(\t\x12\x10\n\x08syllable\x18\x03 \x03(\t\"\x83\x01\n\x08\x41nalysis\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\r\n\x05lemma\x18\x02 \x01(\t\x12(\n\nmorphology\x18\x03 \x03(\x0b\x32\x14.clexicon.Morphology\x12.\n\rpronunciation\x18\x04 \x03(\x0b\x32\x17.clexicon.Pronunciation\"\xbe\x01\n\x08\x43Lexicon\x12\x32\n\x08\x61nalyses\x18\x01 \x03(\x0b\x32 .clexicon.CLexicon.AnalysesEntry\x1a\x30\n\x08\x41nalyses\x12$\n\x08\x61nalysis\x18\x01 \x03(\x0b\x32\x12.clexicon.Analysis\x1aL\n\rAnalysesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.clexicon.CLexicon.Analyses:\x02\x38\x01\x62\x06proto3'
)




_MORPHOLOGY = _descriptor.Descriptor(
  name='Morphology',
  full_name='clexicon.Morphology',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='morph_features', full_name='clexicon.Morphology.morph_features', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clitics', full_name='clexicon.Morphology.clitics', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=99,
)


_CLITIC = _descriptor.Descriptor(
  name='Clitic',
  full_name='clexicon.Clitic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clitic', full_name='clexicon.Clitic.clitic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='morph_features', full_name='clexicon.Clitic.morph_features', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=149,
)


_PRONUNCIATION = _descriptor.Descriptor(
  name='Pronunciation',
  full_name='clexicon.Pronunciation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone', full_name='clexicon.Pronunciation.phone', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='segment', full_name='clexicon.Pronunciation.segment', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='syllable', full_name='clexicon.Pronunciation.syllable', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=216,
)


_ANALYSIS = _descriptor.Descriptor(
  name='Analysis',
  full_name='clexicon.Analysis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='clexicon.Analysis.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lemma', full_name='clexicon.Analysis.lemma', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='morphology', full_name='clexicon.Analysis.morphology', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pronunciation', full_name='clexicon.Analysis.pronunciation', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=350,
)


_CLEXICON_ANALYSES = _descriptor.Descriptor(
  name='Analyses',
  full_name='clexicon.CLexicon.Analyses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='analysis', full_name='clexicon.CLexicon.Analyses.analysis', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=465,
)

_CLEXICON_ANALYSESENTRY = _descriptor.Descriptor(
  name='AnalysesEntry',
  full_name='clexicon.CLexicon.AnalysesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='clexicon.CLexicon.AnalysesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='clexicon.CLexicon.AnalysesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=543,
)

_CLEXICON = _descriptor.Descriptor(
  name='CLexicon',
  full_name='clexicon.CLexicon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='analyses', full_name='clexicon.CLexicon.analyses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CLEXICON_ANALYSES, _CLEXICON_ANALYSESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=543,
)

_MORPHOLOGY.fields_by_name['clitics'].message_type = _CLITIC
_ANALYSIS.fields_by_name['morphology'].message_type = _MORPHOLOGY
_ANALYSIS.fields_by_name['pronunciation'].message_type = _PRONUNCIATION
_CLEXICON_ANALYSES.fields_by_name['analysis'].message_type = _ANALYSIS
_CLEXICON_ANALYSES.containing_type = _CLEXICON
_CLEXICON_ANALYSESENTRY.fields_by_name['value'].message_type = _CLEXICON_ANALYSES
_CLEXICON_ANALYSESENTRY.containing_type = _CLEXICON
_CLEXICON.fields_by_name['analyses'].message_type = _CLEXICON_ANALYSESENTRY
DESCRIPTOR.message_types_by_name['Morphology'] = _MORPHOLOGY
DESCRIPTOR.message_types_by_name['Clitic'] = _CLITIC
DESCRIPTOR.message_types_by_name['Pronunciation'] = _PRONUNCIATION
DESCRIPTOR.message_types_by_name['Analysis'] = _ANALYSIS
DESCRIPTOR.message_types_by_name['CLexicon'] = _CLEXICON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Morphology = _reflection.GeneratedProtocolMessageType('Morphology', (_message.Message,), {
  'DESCRIPTOR' : _MORPHOLOGY,
  '__module__' : 'clexicon_pb2'
  # @@protoc_insertion_point(class_scope:clexicon.Morphology)
  })
_sym_db.RegisterMessage(Morphology)

Clitic = _reflection.GeneratedProtocolMessageType('Clitic', (_message.Message,), {
  'DESCRIPTOR' : _CLITIC,
  '__module__' : 'clexicon_pb2'
  # @@protoc_insertion_point(class_scope:clexicon.Clitic)
  })
_sym_db.RegisterMessage(Clitic)

Pronunciation = _reflection.GeneratedProtocolMessageType('Pronunciation', (_message.Message,), {
  'DESCRIPTOR' : _PRONUNCIATION,
  '__module__' : 'clexicon_pb2'
  # @@protoc_insertion_point(class_scope:clexicon.Pronunciation)
  })
_sym_db.RegisterMessage(Pronunciation)

Analysis = _reflection.GeneratedProtocolMessageType('Analysis', (_message.Message,), {
  'DESCRIPTOR' : _ANALYSIS,
  '__module__' : 'clexicon_pb2'
  # @@protoc_insertion_point(class_scope:clexicon.Analysis)
  })
_sym_db.RegisterMessage(Analysis)

CLexicon = _reflection.GeneratedProtocolMessageType('CLexicon', (_message.Message,), {

  'Analyses' : _reflection.GeneratedProtocolMessageType('Analyses', (_message.Message,), {
    'DESCRIPTOR' : _CLEXICON_ANALYSES,
    '__module__' : 'clexicon_pb2'
    # @@protoc_insertion_point(class_scope:clexicon.CLexicon.Analyses)
    })
  ,

  'AnalysesEntry' : _reflection.GeneratedProtocolMessageType('AnalysesEntry', (_message.Message,), {
    'DESCRIPTOR' : _CLEXICON_ANALYSESENTRY,
    '__module__' : 'clexicon_pb2'
    # @@protoc_insertion_point(class_scope:clexicon.CLexicon.AnalysesEntry)
    })
  ,
  'DESCRIPTOR' : _CLEXICON,
  '__module__' : 'clexicon_pb2'
  # @@protoc_insertion_point(class_scope:clexicon.CLexicon)
  })
_sym_db.RegisterMessage(CLexicon)
_sym_db.RegisterMessage(CLexicon.Analyses)
_sym_db.RegisterMessage(CLexicon.AnalysesEntry)


_CLEXICON_ANALYSESENTRY._options = None
# @@protoc_insertion_point(module_scope)
