# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clexicon_v01.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='clexicon_v01.proto',
  package='clexicon_v01',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63lexicon_v01.proto\x12\x0c\x63lexicon_v01\"[\n\nMorphology\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x16\n\x0emorph_features\x18\x02 \x03(\t\x12%\n\x07\x63litics\x18\x03 \x03(\x0b\x32\x14.clexicon_v01.Clitic\"0\n\x06\x43litic\x12\x0e\n\x06\x63litic\x18\x01 \x01(\t\x12\x16\n\x0emorph_features\x18\x02 \x03(\t\"P\n\rPronunciation\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x03(\t\x12\x10\n\x08syllable\x18\x03 \x03(\t\x12\x0e\n\x06stress\x18\x04 \x01(\t\"{\n\x08\x41nalysis\x12\r\n\x05lemma\x18\x01 \x01(\t\x12,\n\nmorphology\x18\x03 \x03(\x0b\x32\x18.clexicon_v01.Morphology\x12\x32\n\rpronunciation\x18\x04 \x03(\x0b\x32\x1b.clexicon_v01.Pronunciation\"\xca\x01\n\x08\x43Lexicon\x12\x36\n\x08\x61nalyses\x18\x01 \x03(\x0b\x32$.clexicon_v01.CLexicon.AnalysesEntry\x1a\x34\n\x08\x41nalyses\x12(\n\x08\x61nalysis\x18\x01 \x03(\x0b\x32\x16.clexicon_v01.Analysis\x1aP\n\rAnalysesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.clexicon_v01.CLexicon.Analyses:\x02\x38\x01\x62\x06proto3'
)




_MORPHOLOGY = _descriptor.Descriptor(
  name='Morphology',
  full_name='clexicon_v01.Morphology',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='clexicon_v01.Morphology.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='morph_features', full_name='clexicon_v01.Morphology.morph_features', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clitics', full_name='clexicon_v01.Morphology.clitics', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=127,
)


_CLITIC = _descriptor.Descriptor(
  name='Clitic',
  full_name='clexicon_v01.Clitic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clitic', full_name='clexicon_v01.Clitic.clitic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='morph_features', full_name='clexicon_v01.Clitic.morph_features', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=177,
)


_PRONUNCIATION = _descriptor.Descriptor(
  name='Pronunciation',
  full_name='clexicon_v01.Pronunciation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='clexicon_v01.Pronunciation.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phone', full_name='clexicon_v01.Pronunciation.phone', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='syllable', full_name='clexicon_v01.Pronunciation.syllable', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stress', full_name='clexicon_v01.Pronunciation.stress', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=259,
)


_ANALYSIS = _descriptor.Descriptor(
  name='Analysis',
  full_name='clexicon_v01.Analysis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lemma', full_name='clexicon_v01.Analysis.lemma', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='morphology', full_name='clexicon_v01.Analysis.morphology', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pronunciation', full_name='clexicon_v01.Analysis.pronunciation', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=384,
)


_CLEXICON_ANALYSES = _descriptor.Descriptor(
  name='Analyses',
  full_name='clexicon_v01.CLexicon.Analyses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='analysis', full_name='clexicon_v01.CLexicon.Analyses.analysis', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=507,
)

_CLEXICON_ANALYSESENTRY = _descriptor.Descriptor(
  name='AnalysesEntry',
  full_name='clexicon_v01.CLexicon.AnalysesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='clexicon_v01.CLexicon.AnalysesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='clexicon_v01.CLexicon.AnalysesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=509,
  serialized_end=589,
)

_CLEXICON = _descriptor.Descriptor(
  name='CLexicon',
  full_name='clexicon_v01.CLexicon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='analyses', full_name='clexicon_v01.CLexicon.analyses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CLEXICON_ANALYSES, _CLEXICON_ANALYSESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=589,
)

_MORPHOLOGY.fields_by_name['clitics'].message_type = _CLITIC
_ANALYSIS.fields_by_name['morphology'].message_type = _MORPHOLOGY
_ANALYSIS.fields_by_name['pronunciation'].message_type = _PRONUNCIATION
_CLEXICON_ANALYSES.fields_by_name['analysis'].message_type = _ANALYSIS
_CLEXICON_ANALYSES.containing_type = _CLEXICON
_CLEXICON_ANALYSESENTRY.fields_by_name['value'].message_type = _CLEXICON_ANALYSES
_CLEXICON_ANALYSESENTRY.containing_type = _CLEXICON
_CLEXICON.fields_by_name['analyses'].message_type = _CLEXICON_ANALYSESENTRY
DESCRIPTOR.message_types_by_name['Morphology'] = _MORPHOLOGY
DESCRIPTOR.message_types_by_name['Clitic'] = _CLITIC
DESCRIPTOR.message_types_by_name['Pronunciation'] = _PRONUNCIATION
DESCRIPTOR.message_types_by_name['Analysis'] = _ANALYSIS
DESCRIPTOR.message_types_by_name['CLexicon'] = _CLEXICON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Morphology = _reflection.GeneratedProtocolMessageType('Morphology', (_message.Message,), {
  'DESCRIPTOR' : _MORPHOLOGY,
  '__module__' : 'clexicon_v01_pb2'
  # @@protoc_insertion_point(class_scope:clexicon_v01.Morphology)
  })
_sym_db.RegisterMessage(Morphology)

Clitic = _reflection.GeneratedProtocolMessageType('Clitic', (_message.Message,), {
  'DESCRIPTOR' : _CLITIC,
  '__module__' : 'clexicon_v01_pb2'
  # @@protoc_insertion_point(class_scope:clexicon_v01.Clitic)
  })
_sym_db.RegisterMessage(Clitic)

Pronunciation = _reflection.GeneratedProtocolMessageType('Pronunciation', (_message.Message,), {
  'DESCRIPTOR' : _PRONUNCIATION,
  '__module__' : 'clexicon_v01_pb2'
  # @@protoc_insertion_point(class_scope:clexicon_v01.Pronunciation)
  })
_sym_db.RegisterMessage(Pronunciation)

Analysis = _reflection.GeneratedProtocolMessageType('Analysis', (_message.Message,), {
  'DESCRIPTOR' : _ANALYSIS,
  '__module__' : 'clexicon_v01_pb2'
  # @@protoc_insertion_point(class_scope:clexicon_v01.Analysis)
  })
_sym_db.RegisterMessage(Analysis)

CLexicon = _reflection.GeneratedProtocolMessageType('CLexicon', (_message.Message,), {

  'Analyses' : _reflection.GeneratedProtocolMessageType('Analyses', (_message.Message,), {
    'DESCRIPTOR' : _CLEXICON_ANALYSES,
    '__module__' : 'clexicon_v01_pb2'
    # @@protoc_insertion_point(class_scope:clexicon_v01.CLexicon.Analyses)
    })
  ,

  'AnalysesEntry' : _reflection.GeneratedProtocolMessageType('AnalysesEntry', (_message.Message,), {
    'DESCRIPTOR' : _CLEXICON_ANALYSESENTRY,
    '__module__' : 'clexicon_v01_pb2'
    # @@protoc_insertion_point(class_scope:clexicon_v01.CLexicon.AnalysesEntry)
    })
  ,
  'DESCRIPTOR' : _CLEXICON,
  '__module__' : 'clexicon_v01_pb2'
  # @@protoc_insertion_point(class_scope:clexicon_v01.CLexicon)
  })
_sym_db.RegisterMessage(CLexicon)
_sym_db.RegisterMessage(CLexicon.Analyses)
_sym_db.RegisterMessage(CLexicon.AnalysesEntry)


_CLEXICON_ANALYSESENTRY._options = None
# @@protoc_insertion_point(module_scope)
